blueprint:
  name: Heizlogik mit Override
  author: JimnyCricket
  description: |
    ## Heizlogik mit Override

    Manuell freundliche Heizungssteuerung pro Raum.

    Diese Heizlogik setzt auf **Transparenz und Kontrolle**:
    Automationen unterstützen den Alltag, erzwingen aber kein Verhalten.

    **Logik:**
    - Globale Heiz-Saison (Pflicht)
    - Urlaub → ECO
    - Optionaler Zeitplan → Komfort / ECO
    - Optionaler Fensterkontakt mit Verzögerung
    - Ohne Zeitplan bleibt Komfort die Standard-Temperatur

    **Wichtiges Verhalten:**
    - Änderung von Komfort/ECO wirkt sofort, wenn dieser Modus aktiv ist
    - Ohne Zeitplan ist Komfort der Standardbetrieb
    - Fenster schaltet temporär auf ECO (nicht AUS)

    ---
    **Version:** 1.0  
    **Von:** JimnyCricket

  domain: automation

  input:
    heiz_saison:
      name: Heiz-Saison
      selector:
        entity:
          domain: input_boolean

    urlaub:
      name: Urlaub
      selector:
        entity:
          domain: input_boolean

    climate_entity:
      name: Thermostat
      selector:
        entity:
          domain: climate

    komfort_temp:
      name: Komfort-Temperatur
      selector:
        entity:
          domain: input_number

    eco_temp:
      name: ECO-Temperatur
      selector:
        entity:
          domain: input_number

    zeitplan_aktiv:
      name: Zeitplan berücksichtigen?
      default: false
      selector:
        boolean: {}

    zeitplan:
      name: Zeitplan
      default:
      selector:
        entity:
          domain: schedule

    fenster_aktiv:
      name: Fenster berücksichtigen?
      default: false
      selector:
        boolean: {}

    fenster:
      name: Fensterkontakt / Gruppe
      default:
      selector:
        entity:
          domain: binary_sensor

    fenster_verzoegerung:
      name: Fenster-Verzögerung
      default: "00:10:00"
      selector:
        time:

mode: restart

# -------------------------------------------------
# Variablen
# -------------------------------------------------
variables:
  heiz_saison_ent: !input heiz_saison
  urlaub_ent: !input urlaub
  climate_ent: !input climate_entity
  komfort_ent: !input komfort_temp
  eco_ent: !input eco_temp
  zeitplan_ent: !input zeitplan
  zeitplan_enabled: !input zeitplan_aktiv
  fenster_ent: !input fenster
  fenster_enabled: !input fenster_aktiv

# -------------------------------------------------
# Trigger (HA-sicher, optional-fest)
# -------------------------------------------------
trigger:
  # Heiz-Saison
  - platform: state
    entity_id: !input heiz_saison
    to: "on"
    id: season_on

  - platform: state
    entity_id: !input heiz_saison
    to: "off"
    id: season_off

  # Urlaub
  - platform: state
    entity_id: !input urlaub
    to: "on"
    id: vacation_on

  - platform: state
    entity_id: !input urlaub
    to: "off"
    id: vacation_off

  # Temperatur-Helfer
  - platform: state
    entity_id: !input komfort_temp
    id: comfort_temp_changed

  - platform: state
    entity_id: !input eco_temp
    id: eco_temp_changed

  # Zeitplan (optional!)
  - platform: template
    value_template: >
      {{ zeitplan_enabled and zeitplan_ent is not none and is_state(zeitplan_ent, 'on') }}
    id: schedule_on

  - platform: template
    value_template: >
      {{ zeitplan_enabled and zeitplan_ent is not none and is_state(zeitplan_ent, 'off') }}
    id: schedule_off

  # Fenster (optional!)
  - platform: template
    value_template: >
      {{ fenster_enabled and fenster_ent is not none and is_state(fenster_ent, 'on') }}
    for: !input fenster_verzoegerung
    id: window_open

  - platform: template
    value_template: >
      {{ fenster_enabled and fenster_ent is not none and is_state(fenster_ent, 'off') }}
    for: !input fenster_verzoegerung
    id: window_close

# -------------------------------------------------
# Aktionen – ECHT ereignisbasiert
# -------------------------------------------------
action:
  - choose:

      # -------------------------------------------
      # Heiz-Saison AUS → Heizung aus
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: season_off
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: off

      # -------------------------------------------
      # Heiz-Saison AN → Heizung bereit + Zieltemp
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: season_on
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_entity
            data:
              hvac_mode: heat
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input urlaub
                    state: "on"
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ states(eco_ent) | float }}"
              - conditions:
                  - condition: template
                    value_template: >
                      {{ zeitplan_enabled and zeitplan_ent is not none and is_state(zeitplan_ent, 'off') }}
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ states(eco_ent) | float }}"
            default:
              - service: climate.set_temperature
                target:
                  entity_id: !input climate_entity
                data:
                  temperature: "{{ states(komfort_ent) | float }}"

      # -------------------------------------------
      # Urlaub AN → ECO
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: vacation_on
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(eco_ent) | float }}"

      # -------------------------------------------
      # Urlaub AUS → Zeitplan / Default
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: vacation_off
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ zeitplan_enabled and zeitplan_ent is not none and is_state(zeitplan_ent, 'off') }}
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ states(eco_ent) | float }}"
            default:
              - service: climate.set_temperature
                target:
                  entity_id: !input climate_entity
                data:
                  temperature: "{{ states(komfort_ent) | float }}"

      # -------------------------------------------
      # Zeitplan → Komfort
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: schedule_on
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
          - condition: state
            entity_id: !input urlaub
            state: "off"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(komfort_ent) | float }}"

      # -------------------------------------------
      # Zeitplan → ECO
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: schedule_off
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(eco_ent) | float }}"

      # -------------------------------------------
      # Fenster geöffnet → ECO
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: window_open
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(eco_ent) | float }}"

      # -------------------------------------------
      # Fenster geschlossen → Rückkehr
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: window_close
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input urlaub
                    state: "on"
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ states(eco_ent) | float }}"
              - conditions:
                  - condition: template
                    value_template: >
                      {{ zeitplan_enabled and zeitplan_ent is not none and is_state(zeitplan_ent, 'off') }}
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: "{{ states(eco_ent) | float }}"
            default:
              - service: climate.set_temperature
                target:
                  entity_id: !input climate_entity
                data:
                  temperature: "{{ states(komfort_ent) | float }}"

      # -------------------------------------------
      # Komfort-Temperatur geändert → sofort anwenden
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: comfort_temp_changed
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
          - condition: state
            entity_id: !input urlaub
            state: "off"
          - condition: template
            value_template: >
              {{ not zeitplan_enabled or (zeitplan_ent is not none and is_state(zeitplan_ent, 'on')) }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(komfort_ent) | float }}"

      # -------------------------------------------
      # ECO-Temperatur geändert → sofort anwenden
      # -------------------------------------------
      - conditions:
          - condition: trigger
            id: eco_temp_changed
          - condition: state
            entity_id: !input heiz_saison
            state: "on"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(eco_ent) | float }}"
